/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp net.fascode.serenelinux.serene_updater_assistant.dbus.xml -p serene_dbus_interface -a serene_dbus_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "serene_dbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DbusAdaptor
 */

DbusAdaptor::DbusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DbusAdaptor::~DbusAdaptor()
{
    // destructor
}

QString DbusAdaptor::asyncStdOutInvoke(const QString &data)
{
    // handle method call net.fascode.serenelinux.serene_updater_assistant.dbus.asyncStdOutInvoke
    QString out0;
    QMetaObject::invokeMethod(parent(), "asyncStdOutInvoke", Q_RETURN_ARG(QString, out0), Q_ARG(QString, data));
    return out0;
}

QString DbusAdaptor::asyncStdOutSend()
{
    // handle method call net.fascode.serenelinux.serene_updater_assistant.dbus.asyncStdOutSend
    QString data;
    QMetaObject::invokeMethod(parent(), "asyncStdOutSend", Q_RETURN_ARG(QString, data));
    return data;
}

