/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp net.fascode.serenelinux.serene_updater_assistant.dbus.xml -p serene_dbus_interface -a serene_dbus_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERENE_DBUS_ADAPTOR_H_1612441625
#define SERENE_DBUS_ADAPTOR_H_1612441625

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface net.fascode.serenelinux.serene_updater_assistant.dbus
 */
class DbusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "net.fascode.serenelinux.serene_updater_assistant.dbus")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"net.fascode.serenelinux.serene_updater_assistant.dbus\">\n"
"    <!-- QString -->\n"
"    <method name=\"asyncStdOutSend\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"data\"/>\n"
"    </method>\n"
"    <!-- QString -->\n"
"    <method name=\"asyncStdOutInvoke\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"data\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DbusAdaptor(QObject *parent);
    virtual ~DbusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void asyncStdOutInvoke(const QString &data);
    QString asyncStdOutSend();
Q_SIGNALS: // SIGNALS
};

#endif
